# Generated by Django 5.1.7 on 2025-07-13 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0001_initial'),
        ('culturesvegetables', '0003_rename_phase_emerging_kc_culturevegetable_phase_flowering_kc_and_more'),
        ('geolocations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='culturevegetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='culturesvegetables.culturevegetable'),
        ),
        migrations.AlterField(
            model_name='controller',
            name='geolocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geolocations.geolocation'),
        ),
        migrations.AlterField(
            model_name='irrigationcontroller',
            name='culturevegetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='culturesvegetables.culturevegetable'),
        ),
        migrations.AlterField(
            model_name='irrigationcontroller',
            name='geolocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geolocations.geolocation'),
        ),
    ]
