# Generated by Django 5.1.7 on 2025-08-22 00:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0002_alter_controller_culturevegetable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controller',
            name='battery_percentage',
        ),
        migrations.RemoveField(
            model_name='controller',
            name='microcontrolador_code',
        ),
        migrations.AlterField(
            model_name='controller',
            name='valves',
            field=models.PositiveIntegerField(help_text='Quantidade de válvulas operando', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
