# Generated by Django 5.1.7 on 2025-08-23 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0003_remove_controller_battery_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controller',
            name='irrigation_radius',
        ),
        migrations.RemoveField(
            model_name='controller',
            name='plants_per_valve',
        ),
        migrations.RemoveField(
            model_name='controller',
            name='valve_operating',
        ),
        migrations.RemoveField(
            model_name='controller',
            name='valves',
        ),
        migrations.CreateModel(
            name='ValveController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plants_number', models.PositiveIntegerField(help_text='Quantidade de plantas/vegetais irrigados por válvula')),
                ('irrigation_radius', models.FloatField(help_text='Raio de cobertura da irrigação em metros')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação da válvula')),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valves', to='controllers.controller')),
            ],
        ),
    ]
