# Generated by Django 5.1.7 on 2025-08-30 22:30

import controllers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0004_remove_controller_irrigation_radius_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='security_code',
            field=models.CharField(default=controllers.models.generate_security_code, editable=False, max_length=40, unique=True),
        ),
    ]
