# Generated by Django 5.1.7 on 2025-08-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0005_alter_controller_security_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
