# Generated by Django 5.1.7 on 2025-08-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0006_controller_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='valvecontroller',
            name='last_irrigation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
