# Generated by Django 5.1.7 on 2025-08-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0007_valvecontroller_last_irrigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='valvecontroller',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
