# Generated by Django 5.1.7 on 2025-09-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0008_valvecontroller_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='valvecontroller',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
