# Generated by Django 5.1.7 on 2025-09-02 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0009_valvecontroller_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigationcontroller',
            name='controller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='irrigations', to='controllers.controller'),
        ),
    ]
