# Generated by Django 5.1.7 on 2025-09-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0010_alter_irrigationcontroller_controller'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='code',
            field=models.TextField(blank=True, help_text='Código em C do controlador', null=True),
        ),
    ]
