# Generated by Django 5.1.7 on 2025-09-10 00:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0011_controller_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
