# Generated by Django 5.1.7 on 2025-09-10 00:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0012_controller_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
