# Generated by Django 5.1.7 on 2025-09-10 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0013_alter_controller_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controller',
            name='uuid',
        ),
    ]
