# Generated by Django 5.1.7 on 2025-09-11 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0015_controller_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irrigationcontroller',
            name='culturevegetable',
        ),
        migrations.RemoveField(
            model_name='irrigationcontroller',
            name='valves_used',
        ),
        migrations.AddField(
            model_name='irrigationcontroller',
            name='valveController',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='controllers.valvecontroller'),
        ),
    ]
