# Generated by Django 5.1.7 on 2025-09-11 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0016_remove_irrigationcontroller_culturevegetable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='irrigationcontroller',
            old_name='plants_per_valve',
            new_name='plants_number',
        ),
    ]
