# Generated by Django 5.1.7 on 2025-09-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0017_rename_plants_per_valve_irrigationcontroller_plants_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='valvecontroller',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
