# Generated by Django 5.1.7 on 2025-09-12 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0018_valvecontroller_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valvecontroller',
            name='active',
        ),
    ]
