# Generated by Django 5.1.7 on 2025-09-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0019_remove_valvecontroller_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
