# Generated by Django 5.1.7 on 2025-09-13 16:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0020_controller_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
    ]
