# Generated by Django 5.1.7 on 2025-09-13 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0021_alter_controller_uuid'),
        ('culturesvegetables', '0008_remove_culturevegetable_radiusm2'),
    ]

    operations = [
        migrations.AddField(
            model_name='irrigationcontroller',
            name='culturevegetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='culturesvegetables.culturevegetable'),
        ),
    ]
