# Generated by Django 5.1.7 on 2025-09-13 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0022_irrigationcontroller_culturevegetable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='irrigationcontroller',
            old_name='valveController',
            new_name='valvecontroller',
        ),
    ]
