# Generated by Django 5.1.7 on 2025-09-21 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0024_controller_signal_strength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='signal_strength',
            field=models.IntegerField(blank=True, default=0, help_text='Potência do sinal Wi-Fi em dBm (ex: -40 forte, -90 fraco)', null=True, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(0)]),
        ),
    ]
