# Generated by Django 5.1.7 on 2025-09-21 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0025_alter_controller_signal_strength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigationcontroller',
            name='valvecontroller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='irrigations', to='controllers.valvecontroller'),
        ),
    ]
