# Generated by Django 5.1.7 on 2025-10-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0026_alter_irrigationcontroller_valvecontroller'),
    ]

    operations = [
        migrations.AddField(
            model_name='irrigationcontroller',
            name='irrigated_liters',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
