# Generated by Django 5.1.7 on 2025-03-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CultureVegetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phase_germination_kc', models.FloatField()),
                ('phase_vegetative_kc', models.FloatField()),
                ('phase_emergence_kc', models.FloatField()),
                ('phase_frying_kc', models.FloatField()),
                ('phase_maturation_kc', models.FloatField()),
            ],
        ),
    ]
