# Generated by Django 5.1.7 on 2025-04-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culturesvegetables', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='culturevegetable',
            old_name='phase_emergence_kc',
            new_name='phase_emerging_kc',
        ),
    ]
