# Generated by Django 5.1.7 on 2025-06-30 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culturesvegetables', '0002_rename_phase_emergence_kc_culturevegetable_phase_emerging_kc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='culturevegetable',
            old_name='phase_emerging_kc',
            new_name='phase_flowering_kc',
        ),
        migrations.RenameField(
            model_name='culturevegetable',
            old_name='phase_frying_kc',
            new_name='phase_fruiting_kc',
        ),
        migrations.RenameField(
            model_name='culturevegetable',
            old_name='phase_germination_kc',
            new_name='phase_initial_kc',
        ),
    ]
