# Generated by Django 5.1.7 on 2025-08-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturesvegetables', '0003_rename_phase_emerging_kc_culturevegetable_phase_flowering_kc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturevegetable',
            name='radiusM2',
            field=models.FloatField(default=1),
        ),
    ]
