# Generated by Django 5.1.7 on 2025-08-17 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturesvegetables', '0004_culturevegetable_radiusm2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturevegetable',
            name='phase_flowering_kc',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='culturevegetable',
            name='phase_fruiting_kc',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='culturevegetable',
            name='phase_initial_kc',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='culturevegetable',
            name='phase_maturation_kc',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='culturevegetable',
            name='phase_vegetative_kc',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='culturevegetable',
            name='radiusM2',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
