# Generated by Django 5.1.7 on 2025-08-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturesvegetables', '0005_alter_culturevegetable_phase_flowering_kc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturevegetable',
            name='emoji',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
