# Generated by Django 5.1.7 on 2025-08-17 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culturesvegetables', '0006_culturevegetable_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culturevegetable',
            name='emoji',
            field=models.CharField(blank=True, help_text='Escolha um emoji para representar a cultura.', max_length=2, null=True, validators=[django.core.validators.RegexValidator(message='Coloque apenas 1 emoji válido.', regex='^[\\U0001F300-\\U0001FAFF]$')]),
        ),
    ]
