# Generated by Django 5.1.7 on 2025-09-10 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culturesvegetables', '0007_alter_culturevegetable_emoji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culturevegetable',
            name='radiusM2',
        ),
    ]
