# Generated by Django 5.1.7 on 2025-08-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='favorite',
            field=models.BooleanField(default=0),
        ),
    ]
