# Generated by Django 5.1.7 on 2025-10-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocations', '0002_geolocation_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='property_name',
            field=models.CharField(default='Fazenda', max_length=255),
        ),
    ]
