# Generated by Django 5.1.7 on 2025-07-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_log_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='viewed',
            field=models.BooleanField(default=0),
        ),
    ]
