# Generated by Django 5.1.7 on 2025-03-25 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geolocations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeteorologicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_max', models.FloatField()),
                ('temperature_min', models.FloatField()),
                ('relative_humidity', models.FloatField()),
                ('solar_radiation', models.FloatField()),
                ('air_speed', models.FloatField()),
                ('date', models.DateField(auto_now=True)),
                ('geolocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geolocations.geolocation')),
            ],
        ),
    ]
