# Generated by Django 5.1.7 on 2025-04-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteorologicaldatas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteorologicaldata',
            name='pressure',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
