# Generated by Django 5.1.7 on 2025-03-25 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('culturesvegetables', '0001_initial'),
        ('meteorologicaldatas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrrigationVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_germination', models.FloatField()),
                ('phase_vegetative', models.FloatField()),
                ('phase_emergence', models.FloatField()),
                ('phase_frying', models.FloatField()),
                ('phase_maturation', models.FloatField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('culturevegetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culturesvegetables.culturevegetable')),
                ('meteorologicaldata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meteorologicaldatas.meteorologicaldata')),
            ],
        ),
    ]
