# Generated by Django 5.1.7 on 2025-03-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigationvolumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigationvolume',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
