# Generated by Django 5.1.7 on 2025-06-30 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irrigationvolumes', '0003_rename_phase_emergence_irrigationvolume_phase_emerging'),
    ]

    operations = [
        migrations.RenameField(
            model_name='irrigationvolume',
            old_name='phase_emerging',
            new_name='phase_flowering',
        ),
        migrations.RenameField(
            model_name='irrigationvolume',
            old_name='phase_frying',
            new_name='phase_fruiting',
        ),
        migrations.RenameField(
            model_name='irrigationvolume',
            old_name='phase_germination',
            new_name='phase_initial',
        ),
    ]
