# Generated by Django 5.1.7 on 2025-07-13 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigationvolumes', '0004_rename_phase_emerging_irrigationvolume_phase_flowering_and_more'),
        ('meteorologicaldatas', '0002_meteorologicaldata_pressure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigationvolume',
            name='meteorologicaldata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meteorologicaldatas.meteorologicaldata'),
        ),
    ]
