# Generated by Django 5.1.7 on 2025-07-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigationvolumes', '0005_alter_irrigationvolume_meteorologicaldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigationvolume',
            name='date',
            field=models.DateField(),
        ),
    ]
